image:
  file: gitpod.dockerfile
tasks:
  - before: npm install
  - command: mongod --dbpath data/ --journal --port 27017;
  - command: redis-server --port 6379;
  - command: npm start
ports:
  - port: 27017
  - port: 6379
  - port: 3000
    onOpen: open-preview
